# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24c82f1ac5257d155809beaacb5558d88f99e6fb464fb72e41fa874160c89c56c6eff03d8dd0fe853cf85198bd7779b22a450c51220965685f27dbeb47c6250e

test:
  secret_key_base: 9ecf2918ede60eee806eddbfea6c91834a864c95b8f8e3d0176a8b3a88b11256de479229bceb8a4e9726151d8c2687531b7e44a8b0c1de2f5c1b8f2317577973

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
